spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/cms_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    generate-ddl: false
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
logging:
  level:
    org.springframework.security: DEBUG
application:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
  bin:
    visa: ${VISA_BIN}
    master: ${MASTER_BIN}
    mir: ${MIR_BIN}
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha